### ISSUE TITLE
[server process manager] 500 error

### ISSUE THREAD

**Issue by christinerogers** [aces/loris-demo-project#29]
I can't find it now, but I think there was a 500 error on this module in round 1 of Release 21 testing? 
Was it due to the missing config Options in RaisingBread from the wonky 20.1->20.2 upgrade?

**Comment by ridz1208** [comment]
fixed, demo was missing the /data/demo/bin/mri directory

**Comment by christinerogers** [comment]
confirmed fixed.  thanks.
