### ISSUE TITLE
[Img Browser] Feedback mri popup is blank 

### ISSUE THREAD

**Issue by christinerogers** [aces/loris-demo-project#31]
Under each scan, the QC comments button triggers a popup, e.g. 
https://demo.loris.ca/feedback_mri_popup.php?fileID=238

The content of this window is blank.  It shoudl show all the checkboxes...

Don't see any aces/loris issues on this, so perhaps it's just on Demo?

**Comment by cmadjar** [comment]
I just tested it and I see the windows correctly. Which browser are you using?

**Comment by christinerogers** [comment]
chrome.  works now.  thanks
