### ISSUE TITLE
Still 500 error on Reliability module 

### ISSUE THREAD

**Issue by christinerogers** [aces/loris-demo-project#35]
This issue was closed(resolved) May 31 -- It is actually still an issue on demo: 
https://github.com/aces/loris-demo-project/issues/25

Extra points to @coreyAbout for finding it! 

p.s. @ridz1208 would you be willing to let me re-open ticket ? 
Can we add @coreyAbout to this repo?  He's a great tester and is sure to find more issues.

**Comment by ridz1208** [comment]
reliability is gone
