### ISSUE TITLE
Broken icons across all modules on Demo 

### ISSUE THREAD

**Issue by christinerogers** [aces/loris-demo-project#36]
on http://demo.loris.ca/ - Some icon images not loading.  

Important Examples below: Imaging Browser (**Pass/Fail** is not visible, yikes) and Dashboard 

Generally: Breadcrumb bar ">" and Menu Filter bar "^" icons not loading across modules. 

<img width="550" alt="ImgBrowser_icons" src="https://user-images.githubusercontent.com/827619/63468284-7e225200-c435-11e9-9874-44283a10cefd.png">

<img width="700" alt="Demo_dashboard_icons" src="https://user-images.githubusercontent.com/827619/63468063-e7559580-c434-11e9-8139-dbc2770a8788.png">

**Comment by ridz1208** [comment]
<img width="1680" alt="Screen Shot 2019-08-30 at 1 35 22 PM" src="https://user-images.githubusercontent.com/15268287/64040449-105be180-cb2b-11e9-867d-ec96be23445f.png">
